pipeline {
    agent any

    // Define environment variables
    environment {
        PYTHON_VERSIONS = "3.8 3.9 3.10"  
        DOCKERHUB_CREDENTIALS = "" //dockerhub_credentials 
        REPO_NAME = "" //your-dockerhub-username/your-repository 
    }

    stages {
        stage('Install Dependencies') {
            agent {
                docker {
                    image 'python:3.10' 
                    args '--mount type=bind,source=$HOME/.cache/pip,target=/root/.cache/pip' 
                }
            }
            steps {
                sh 'pip install -r requirements.txt' 
            }
        }

        stage('Test Application') {
            matrix {
                axes {
                    axis {
                        name 'PYTHON_VERSION'
                        values '3.8', '3.9', '3.10' 
                    }
                }
                stages {
                    stage('Run Test') {
                        agent {
                            docker {
                                image "python:${PYTHON_VERSION}" 
                                reuseNode true
                            }
                        }
                        steps {
                            sh 'python -m unittest discover tests/' 
                        }
                    }
                }
            }
        }

        stage('Build Docker Images') {
            matrix {
                axes {
                    axis {
                        name 'PYTHON_VERSION'
                        values '3.8', '3.9', '3.10'
                    }
                }
                stages {
                    stage('Build Image') {
                        steps {
                            sh """
                            docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} -t ${REPO_NAME}:${PYTHON_VERSION} .
                            """
                        }
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            matrix {
                axes {
                    axis {
                        name 'PYTHON_VERSION'
                        values '3.8', '3.9', '3.10'
                    }
                }
                stages {
                    stage('Push Image') {
                        steps {
                            script {
                                docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS) {
                                    sh "docker push ${REPO_NAME}:${PYTHON_VERSION}"
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            sh "docker system prune -f" 
        }
    }
}
